[2024-04-15T21:09:21.806-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T21:09:21.814-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_dag.build_graph scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T21:09:21.818-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_dag.build_graph scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T21:09:21.818-0400] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T21:09:21.825-0400] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): build_graph> on 2024-04-14 00:00:00+00:00
[2024-04-15T21:09:21.829-0400] {standard_task_runner.py:63} INFO - Started process 54078 to run task
[2024-04-15T21:09:21.834-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_dag', 'build_graph', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/preprocessing_dag.py', '--cfg-path', '/var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T/tmpls7pyi4h']
[2024-04-15T21:09:21.836-0400] {standard_task_runner.py:91} INFO - Job 277: Subtask build_graph
[2024-04-15T21:09:21.874-0400] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_dag.build_graph scheduled__2024-04-14T00:00:00+00:00 [running]> on host manis-macbook-air.local
[2024-04-15T21:09:21.913-0400] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='preprocessing_dag' AIRFLOW_CTX_TASK_ID='build_graph' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T21:09:21.914-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T21:09:21.924-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T21:09:21.925-0400] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/cap_airflow/dags/preprocessing_dag.py", line 42, in python_task_2
    create_graph.main()
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'create_graph' has no attribute 'main'
[2024-04-15T21:09:21.934-0400] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=preprocessing_dag, task_id=build_graph, execution_date=20240414T000000, start_date=20240416T010921, end_date=20240416T010921
[2024-04-15T21:09:21.939-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 277 for task build_graph (module 'create_graph' has no attribute 'main'; 54078)
[2024-04-15T21:09:21.985-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T21:09:21.993-0400] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T21:09:21.993-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
