[2024-04-15T14:09:08.248-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T14:09:08.262-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-15T14:09:08.264-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-15T14:09:08.264-0400] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T14:09:08.268-0400] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task> on 2024-01-16 00:00:00+00:00
[2024-04-15T14:09:08.273-0400] {standard_task_runner.py:63} INFO - Started process 48639 to run task
[2024-04-15T14:09:08.277-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_dag', 'bash_task', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/preprocessing_dag.py', '--cfg-path', '/var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T/tmpgxximgjk']
[2024-04-15T14:09:08.279-0400] {standard_task_runner.py:91} INFO - Job 74: Subtask bash_task
[2024-04-15T14:09:08.299-0400] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_dag.bash_task scheduled__2024-01-16T00:00:00+00:00 [running]> on host manis-macbook-air.local
[2024-04-15T14:09:08.321-0400] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='preprocessing_dag' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-04-15T14:09:08.322-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T14:09:08.322-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T
[2024-04-15T14:09:08.323-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/cap_dbt && dbt run']
[2024-04-15T14:09:08.328-0400] {subprocess.py:86} INFO - Output:
[2024-04-15T14:09:09.847-0400] {subprocess.py:93} INFO - [0m18:09:09  Running with dbt=1.7.11
[2024-04-15T14:09:10.812-0400] {subprocess.py:93} INFO - [0m18:09:10  Registered adapter: snowflake=1.7.3
[2024-04-15T14:09:10.938-0400] {subprocess.py:93} INFO - [0m18:09:10  Found 3 models, 1 source, 0 exposures, 0 metrics, 544 macros, 0 groups, 0 semantic models
[2024-04-15T14:09:10.940-0400] {subprocess.py:93} INFO - [0m18:09:10
[2024-04-15T14:26:32.794-0400] {subprocess.py:93} INFO - [0m18:26:32
[2024-04-15T14:26:32.794-0400] {subprocess.py:93} INFO - [0m18:26:32  Finished running  in 0 hours 17 minutes and 21.85 seconds (1041.85s).
[2024-04-15T14:26:32.795-0400] {subprocess.py:93} INFO - [0m18:26:32  Encountered an error:
[2024-04-15T14:26:32.795-0400] {subprocess.py:93} INFO - Runtime Error
[2024-04-15T14:26:32.795-0400] {subprocess.py:93} INFO -   Database error while listing schemas in database "CAP"
[2024-04-15T14:26:32.796-0400] {subprocess.py:93} INFO -   Database Error
[2024-04-15T14:26:32.796-0400] {subprocess.py:93} INFO -     250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
[2024-04-15T14:26:33.188-0400] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-15T14:26:33.191-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T14:26:33.236-0400] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-15T14:26:33.262-0400] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_dag, task_id=bash_task, execution_date=20240116T000000, start_date=20240415T180908, end_date=20240415T182633
[2024-04-15T14:26:33.288-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task bash_task (Bash command failed. The command returned a non-zero exit code 2.; 48639)
[2024-04-15T14:26:33.317-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T14:26:33.392-0400] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T14:26:33.394-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
