[2024-04-15T19:13:25.703-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T19:13:25.723-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-04-15T19:13:25.727-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-04-15T19:13:25.727-0400] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T19:13:25.733-0400] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task> on 2024-02-18 00:00:00+00:00
[2024-04-15T19:13:25.738-0400] {standard_task_runner.py:63} INFO - Started process 49858 to run task
[2024-04-15T19:13:25.742-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_dag', 'bash_task', 'scheduled__2024-02-18T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/preprocessing_dag.py', '--cfg-path', '/var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T/tmpx8ph45ys']
[2024-04-15T19:13:25.744-0400] {standard_task_runner.py:91} INFO - Job 147: Subtask bash_task
[2024-04-15T19:13:25.769-0400] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-18T00:00:00+00:00 [running]> on host manis-macbook-air.local
[2024-04-15T19:13:25.807-0400] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='preprocessing_dag' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-18T00:00:00+00:00'
[2024-04-15T19:13:25.808-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T19:13:25.808-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T
[2024-04-15T19:13:25.809-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/cap_dbt && dbt run']
[2024-04-15T19:13:25.815-0400] {subprocess.py:86} INFO - Output:
[2024-04-15T19:13:27.575-0400] {subprocess.py:93} INFO - [0m23:13:27  Running with dbt=1.7.11
[2024-04-15T19:13:28.960-0400] {subprocess.py:93} INFO - [0m23:13:28  Registered adapter: snowflake=1.7.3
[2024-04-15T19:13:29.145-0400] {subprocess.py:93} INFO - [0m23:13:29  Found 3 models, 1 source, 0 exposures, 0 metrics, 544 macros, 0 groups, 0 semantic models
[2024-04-15T19:13:29.146-0400] {subprocess.py:93} INFO - [0m23:13:29
[2024-04-15T19:13:31.348-0400] {subprocess.py:93} INFO - [0m23:13:31  Concurrency: 1 threads (target='dev')
[2024-04-15T19:13:31.350-0400] {subprocess.py:93} INFO - [0m23:13:31
[2024-04-15T19:13:31.351-0400] {subprocess.py:93} INFO - [0m23:13:31  1 of 3 START sql view model DEV.raw_data_processing ............................ [RUN]
[2024-04-15T19:40:24.744-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-15T19:40:24.755-0400] {process_utils.py:132} INFO - Sending 15 to group 49858. PIDs of all processes in the group: [49859, 49860, 49864, 49858]
[2024-04-15T19:40:24.756-0400] {process_utils.py:87} INFO - Sending the signal 15 to group 49858
[2024-04-15T19:40:24.757-0400] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-15T19:40:24.766-0400] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-15T19:40:24.774-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T19:40:24.784-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=49860, status='terminated', started='19:13:25') (49860) terminated with exit code None
[2024-04-15T19:40:24.795-0400] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-15T19:40:24.821-0400] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_dag, task_id=bash_task, execution_date=20240218T000000, start_date=20240415T231325, end_date=20240415T234024
[2024-04-15T19:40:24.857-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=49858, status='terminated', exitcode=2, started='19:13:25') (49858) terminated with exit code 2
[2024-04-15T19:40:24.858-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=49864, status='terminated', started='19:13:28') (49864) terminated with exit code None
[2024-04-15T19:40:24.858-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=49859, status='terminated', started='19:13:25') (49859) terminated with exit code None
