[2024-04-15T20:27:40.636-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T20:27:40.652-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-04-15T20:27:40.655-0400] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-04-15T20:27:40.655-0400] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T20:27:40.661-0400] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task> on 2024-02-29 00:00:00+00:00
[2024-04-15T20:27:40.665-0400] {standard_task_runner.py:63} INFO - Started process 52333 to run task
[2024-04-15T20:27:40.668-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_dag', 'bash_task', 'scheduled__2024-02-29T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/preprocessing_dag.py', '--cfg-path', '/var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T/tmp9eo5oopz']
[2024-04-15T20:27:40.671-0400] {standard_task_runner.py:91} INFO - Job 172: Subtask bash_task
[2024-04-15T20:27:40.699-0400] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_dag.bash_task scheduled__2024-02-29T00:00:00+00:00 [running]> on host manis-macbook-air.local
[2024-04-15T20:27:40.744-0400] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='preprocessing_dag' AIRFLOW_CTX_TASK_ID='bash_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:00:00+00:00'
[2024-04-15T20:27:40.745-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T20:27:40.760-0400] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/rf/bv8hf2w15f1f30n5rv6mfypr0000gn/T
[2024-04-15T20:27:40.761-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/cap_dbt && dbt run']
[2024-04-15T20:27:40.770-0400] {subprocess.py:86} INFO - Output:
[2024-04-15T20:27:43.273-0400] {subprocess.py:93} INFO - [0m00:27:43  Running with dbt=1.7.11
[2024-04-15T20:31:07.733-0400] {subprocess.py:93} INFO - [0m00:31:07  Registered adapter: snowflake=1.7.3
[2024-04-15T20:31:08.032-0400] {subprocess.py:93} INFO - [0m00:31:08  Found 3 models, 1 source, 0 exposures, 0 metrics, 544 macros, 0 groups, 0 semantic models
[2024-04-15T20:31:08.035-0400] {subprocess.py:93} INFO - [0m00:31:08
[2024-04-15T20:31:09.129-0400] {subprocess.py:93} INFO - [0m00:31:09
[2024-04-15T20:31:09.145-0400] {subprocess.py:93} INFO - [0m00:31:09  Finished running  in 0 hours 0 minutes and 1.09 seconds (1.09s).
[2024-04-15T20:31:09.147-0400] {subprocess.py:93} INFO - [0m00:31:09  Encountered an error:
[2024-04-15T20:31:09.155-0400] {subprocess.py:93} INFO - Runtime Error
[2024-04-15T20:31:09.164-0400] {subprocess.py:93} INFO -   Database error while listing schemas in database "CAP"
[2024-04-15T20:31:09.174-0400] {subprocess.py:93} INFO -   Database Error
[2024-04-15T20:31:09.182-0400] {subprocess.py:93} INFO -     250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
[2024-04-15T20:31:09.633-0400] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-15T20:31:09.645-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T20:31:09.792-0400] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manideepakreddyaila/Desktop/projects/Legal_Insights_Engine/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-15T20:31:09.832-0400] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_dag, task_id=bash_task, execution_date=20240229T000000, start_date=20240416T002740, end_date=20240416T003109
[2024-04-15T20:31:09.886-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 172 for task bash_task (Bash command failed. The command returned a non-zero exit code 2.; 52333)
[2024-04-15T20:31:09.924-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T20:31:09.937-0400] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T20:31:09.937-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
